%% Import data from text file.
% Script for importing data from the following text file:
%
%    C:\Users\lab\Desktop\UP Akwizycja\bin\Debug\probki.txt
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2018/11/20 16:10:53

%% Initialize variables.
filename = 'C:\Users\lab\Desktop\New folder\program\akwizycja\matlab\probki.txt';
delimiter = '';

%% Format for each line of text:
%   column1: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to the format.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, 'Delimiter', delimiter, 'MultipleDelimsAsOne', true, 'TextType', 'string',  'ReturnOnError', false);

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Create output variable
probki = table(dataArray{1:end-1}, 'VariableNames', {'VarName1'});

%% Clear temporary variables
clearvars filename delimiter formatSpec fileID dataArray ans;

fpr = 100;
Tp = 1/100;

%y = linspace(0,100,100);
x = linspace(0,256, 256);
figure
plot (x,probki.VarName1);
%plot (y,probki.VarName1);